[package]
name = "phone_adventures"
version = "0.1.0"

[dependencies]
pom      = "3"
rouille  = "3"
url      = "1.7"

[lib]
name = "phone_adventures"
path = "src/main/rust/lib.rs"

[[bin]]
name = "phone_adventures_server"
path = "src/main/rust/main.rs"
